# Generated by Django 3.0.4 on 2020-04-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shift_worked',
        ),
        migrations.AddField(
            model_name='manager',
            name='pending_timesheets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zapp.Timesheet'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='friday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='monday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='thursday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='tuesday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='wednesday',
            field=models.IntegerField(default=0),
        ),
    ]
