# Generated by Django 3.0.4 on 2020-04-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0002_auto_20200409_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='pending_timesheets',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_timesheets', to='zapp.Manager'),
        ),
    ]
