# Generated by Django 3.0.4 on 2020-04-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0003_auto_20200409_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='manager',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approved_status',
            field=models.BooleanField(default=False),
        ),
    ]
