# Generated by Django 3.0.4 on 2020-04-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0004_auto_20200409_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'permissions': [('can_approve', 'Can approve timesheets'), ('can_search', "Can search employees' timesheets")]},
        ),
    ]
