# Generated by Django 3.0.4 on 2020-04-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0005_auto_20200413_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='username',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
